version: '3.3'
services:
  climatology:
    build:
      context: .
      dockerfile: Dockerfile
    image: climatology:latest
    container_name: climatology
    platform: linux/amd64
    volumes:
      - .:/home
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    entrypoint: python3 climoDL.py
    command: python3 climoDL.py -h