name: Render and deploy Quarto files
on:
  push: 
    branches: main

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
        
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - run: |
        pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install clipy/dist/clipy-2025.0.1-py3-none-any.whl
    
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      
    - name: Publish to GitHub Pages (and render)
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
